<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Details</title>
</head>
<body>
<h1>Details</h1>
<dl>
    <dt>Id</dt>
    <dd>${moto.id()}</dd>
    <dt>Brand</dt>
    <dd>${moto.brand()}</dd>
    <dt>Model</dt>
    <dd>${moto.model()}</dd>
    <dt>Power</dt>
    <dd>${moto.power()}</dd>
</dl>
<a href="/moto">Back to list</a>
</body>
</html>