<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>Home</title>
    <style>
    </style>
</head>
<body>
<nav>
    <a href="/home">Home</a>
    <a href="/home/about">About</a>
    <a href="/tf/java/thebest">The Best</a>
</nav>
<h1>Hello world</h1>
</body>
</html>